version: '3'
services:
  service-discovery:
    image: eureka-server:latest
    ports:
     - "8761:8761"
  worker-service:
    image: hello-service:latest
    environment:
      - EUREKA_HOST=service-discovery
      - EUREKA_PORT=8761
  user-service:
    image: user-service:latest
    ports:
      - "7211:7211"
    environment:
      - EUREKA_HOST=service-discovery
      - EUREKA_PORT=8761
  js-eureka-service:
    image: js-eureka-client:latest
    ports:
      - "3000:3000"
    environment:
      - EUREKA_HOST=service-discovery
      - EUREKA_PORT=8761
      - USER_SERVICE_URI=user-service:7211