spring:
  application:
    name: gateway

server:
  port: 8080

uri:
  userService: http://${USER_SERVICE_URI}
  secondService: http://${SECOND_SERVICE_URI}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
    instance:
      leaseRenewalIntervalInSeconds: 10
      metadataMap:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
